/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlotSize = {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "sqm500";
    sqm500: null;
} | {
    __kind__: "sqm1000";
    sqm1000: null;
} | {
    __kind__: "sqm2000";
    sqm2000: null;
} | {
    __kind__: "sqm5000";
    sqm5000: null;
};
export interface Enquiry {
    contactPerson: string;
    investmentTimeline: InvestmentTimeline;
    email: string;
    powerRequirement: string;
    companyName: string;
    phone: string;
    industryType: IndustryType;
    plotSize: PlotSize;
}
export enum IndustryType {
    logistics = "logistics",
    warehousing = "warehousing",
    other = "other",
    fmcg = "fmcg",
    engineering = "engineering",
    coldStorage = "coldStorage",
    manufacturing = "manufacturing",
    pharma = "pharma",
    packaging = "packaging"
}
export enum InvestmentTimeline {
    months12Plus = "months12Plus",
    months3To6 = "months3To6",
    immediate = "immediate",
    months6To12 = "months6To12"
}
export interface backendInterface {
    getEnquiries(): Promise<Array<Enquiry>>;
    submitEnquiry(companyName: string, contactPerson: string, phone: string, email: string, industryType: IndustryType, plotSize: PlotSize, powerRequirement: string, investmentTimeline: InvestmentTimeline): Promise<void>;
}
import type { Enquiry as _Enquiry, IndustryType as _IndustryType, InvestmentTimeline as _InvestmentTimeline, PlotSize as _PlotSize } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: IndustryType, arg5: PlotSize, arg6: string, arg7: InvestmentTimeline): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_IndustryType_n10(this._uploadFile, this._downloadFile, arg4), to_candid_PlotSize_n12(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_InvestmentTimeline_n14(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, to_candid_IndustryType_n10(this._uploadFile, this._downloadFile, arg4), to_candid_PlotSize_n12(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_InvestmentTimeline_n14(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_Enquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_IndustryType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndustryType): IndustryType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentTimeline_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentTimeline): InvestmentTimeline {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PlotSize_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlotSize): PlotSize {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactPerson: string;
    investmentTimeline: _InvestmentTimeline;
    email: string;
    powerRequirement: string;
    companyName: string;
    phone: string;
    industryType: _IndustryType;
    plotSize: _PlotSize;
}): {
    contactPerson: string;
    investmentTimeline: InvestmentTimeline;
    email: string;
    powerRequirement: string;
    companyName: string;
    phone: string;
    industryType: IndustryType;
    plotSize: PlotSize;
} {
    return {
        contactPerson: value.contactPerson,
        investmentTimeline: from_candid_InvestmentTimeline_n4(_uploadFile, _downloadFile, value.investmentTimeline),
        email: value.email,
        powerRequirement: value.powerRequirement,
        companyName: value.companyName,
        phone: value.phone,
        industryType: from_candid_IndustryType_n6(_uploadFile, _downloadFile, value.industryType),
        plotSize: from_candid_PlotSize_n8(_uploadFile, _downloadFile, value.plotSize)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    months12Plus: null;
} | {
    months3To6: null;
} | {
    immediate: null;
} | {
    months6To12: null;
}): InvestmentTimeline {
    return "months12Plus" in value ? InvestmentTimeline.months12Plus : "months3To6" in value ? InvestmentTimeline.months3To6 : "immediate" in value ? InvestmentTimeline.immediate : "months6To12" in value ? InvestmentTimeline.months6To12 : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logistics: null;
} | {
    warehousing: null;
} | {
    other: null;
} | {
    fmcg: null;
} | {
    engineering: null;
} | {
    coldStorage: null;
} | {
    manufacturing: null;
} | {
    pharma: null;
} | {
    packaging: null;
}): IndustryType {
    return "logistics" in value ? IndustryType.logistics : "warehousing" in value ? IndustryType.warehousing : "other" in value ? IndustryType.other : "fmcg" in value ? IndustryType.fmcg : "engineering" in value ? IndustryType.engineering : "coldStorage" in value ? IndustryType.coldStorage : "manufacturing" in value ? IndustryType.manufacturing : "pharma" in value ? IndustryType.pharma : "packaging" in value ? IndustryType.packaging : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: bigint;
} | {
    sqm500: null;
} | {
    sqm1000: null;
} | {
    sqm2000: null;
} | {
    sqm5000: null;
}): {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "sqm500";
    sqm500: null;
} | {
    __kind__: "sqm1000";
    sqm1000: null;
} | {
    __kind__: "sqm2000";
    sqm2000: null;
} | {
    __kind__: "sqm5000";
    sqm5000: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "sqm500" in value ? {
        __kind__: "sqm500",
        sqm500: value.sqm500
    } : "sqm1000" in value ? {
        __kind__: "sqm1000",
        sqm1000: value.sqm1000
    } : "sqm2000" in value ? {
        __kind__: "sqm2000",
        sqm2000: value.sqm2000
    } : "sqm5000" in value ? {
        __kind__: "sqm5000",
        sqm5000: value.sqm5000
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_IndustryType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndustryType): _IndustryType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_InvestmentTimeline_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentTimeline): _InvestmentTimeline {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PlotSize_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlotSize): _PlotSize {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndustryType): {
    logistics: null;
} | {
    warehousing: null;
} | {
    other: null;
} | {
    fmcg: null;
} | {
    engineering: null;
} | {
    coldStorage: null;
} | {
    manufacturing: null;
} | {
    pharma: null;
} | {
    packaging: null;
} {
    return value == IndustryType.logistics ? {
        logistics: null
    } : value == IndustryType.warehousing ? {
        warehousing: null
    } : value == IndustryType.other ? {
        other: null
    } : value == IndustryType.fmcg ? {
        fmcg: null
    } : value == IndustryType.engineering ? {
        engineering: null
    } : value == IndustryType.coldStorage ? {
        coldStorage: null
    } : value == IndustryType.manufacturing ? {
        manufacturing: null
    } : value == IndustryType.pharma ? {
        pharma: null
    } : value == IndustryType.packaging ? {
        packaging: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "sqm500";
    sqm500: null;
} | {
    __kind__: "sqm1000";
    sqm1000: null;
} | {
    __kind__: "sqm2000";
    sqm2000: null;
} | {
    __kind__: "sqm5000";
    sqm5000: null;
}): {
    custom: bigint;
} | {
    sqm500: null;
} | {
    sqm1000: null;
} | {
    sqm2000: null;
} | {
    sqm5000: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "sqm500" ? {
        sqm500: value.sqm500
    } : value.__kind__ === "sqm1000" ? {
        sqm1000: value.sqm1000
    } : value.__kind__ === "sqm2000" ? {
        sqm2000: value.sqm2000
    } : value.__kind__ === "sqm5000" ? {
        sqm5000: value.sqm5000
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentTimeline): {
    months12Plus: null;
} | {
    months3To6: null;
} | {
    immediate: null;
} | {
    months6To12: null;
} {
    return value == InvestmentTimeline.months12Plus ? {
        months12Plus: null
    } : value == InvestmentTimeline.months3To6 ? {
        months3To6: null
    } : value == InvestmentTimeline.immediate ? {
        immediate: null
    } : value == InvestmentTimeline.months6To12 ? {
        months6To12: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
