/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InvestmentTimeline = IDL.Variant({
  'months12Plus' : IDL.Null,
  'months3To6' : IDL.Null,
  'immediate' : IDL.Null,
  'months6To12' : IDL.Null,
});
export const IndustryType = IDL.Variant({
  'logistics' : IDL.Null,
  'warehousing' : IDL.Null,
  'other' : IDL.Null,
  'fmcg' : IDL.Null,
  'engineering' : IDL.Null,
  'coldStorage' : IDL.Null,
  'manufacturing' : IDL.Null,
  'pharma' : IDL.Null,
  'packaging' : IDL.Null,
});
export const PlotSize = IDL.Variant({
  'custom' : IDL.Nat,
  'sqm500' : IDL.Null,
  'sqm1000' : IDL.Null,
  'sqm2000' : IDL.Null,
  'sqm5000' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'contactPerson' : IDL.Text,
  'investmentTimeline' : InvestmentTimeline,
  'email' : IDL.Text,
  'powerRequirement' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'industryType' : IndustryType,
  'plotSize' : PlotSize,
});

export const idlService = IDL.Service({
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'submitEnquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IndustryType,
        PlotSize,
        IDL.Text,
        InvestmentTimeline,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InvestmentTimeline = IDL.Variant({
    'months12Plus' : IDL.Null,
    'months3To6' : IDL.Null,
    'immediate' : IDL.Null,
    'months6To12' : IDL.Null,
  });
  const IndustryType = IDL.Variant({
    'logistics' : IDL.Null,
    'warehousing' : IDL.Null,
    'other' : IDL.Null,
    'fmcg' : IDL.Null,
    'engineering' : IDL.Null,
    'coldStorage' : IDL.Null,
    'manufacturing' : IDL.Null,
    'pharma' : IDL.Null,
    'packaging' : IDL.Null,
  });
  const PlotSize = IDL.Variant({
    'custom' : IDL.Nat,
    'sqm500' : IDL.Null,
    'sqm1000' : IDL.Null,
    'sqm2000' : IDL.Null,
    'sqm5000' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'contactPerson' : IDL.Text,
    'investmentTimeline' : InvestmentTimeline,
    'email' : IDL.Text,
    'powerRequirement' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'industryType' : IndustryType,
    'plotSize' : PlotSize,
  });
  
  return IDL.Service({
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'submitEnquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IndustryType,
          PlotSize,
          IDL.Text,
          InvestmentTimeline,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };