/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'contactPerson' : string,
  'investmentTimeline' : InvestmentTimeline,
  'email' : string,
  'powerRequirement' : string,
  'companyName' : string,
  'phone' : string,
  'industryType' : IndustryType,
  'plotSize' : PlotSize,
}
export type IndustryType = { 'logistics' : null } |
  { 'warehousing' : null } |
  { 'other' : null } |
  { 'fmcg' : null } |
  { 'engineering' : null } |
  { 'coldStorage' : null } |
  { 'manufacturing' : null } |
  { 'pharma' : null } |
  { 'packaging' : null };
export type InvestmentTimeline = { 'months12Plus' : null } |
  { 'months3To6' : null } |
  { 'immediate' : null } |
  { 'months6To12' : null };
export type PlotSize = { 'custom' : bigint } |
  { 'sqm500' : null } |
  { 'sqm1000' : null } |
  { 'sqm2000' : null } |
  { 'sqm5000' : null };
export interface _SERVICE {
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'submitEnquiry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      IndustryType,
      PlotSize,
      string,
      InvestmentTimeline,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];